# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 7.2
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# Dependencies
before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: composer test
